# About this course

This introduction course, presented for the first time in BIBDA Master, tends to give you an overview of Python programming language and its general structure as in the future modules of Master like web scrapping, Machine learning and text mining Python will be used as the principal programming language.
Please note that due to the vast range of arguments/tools related to Python language we won't/can't cover them all here as this course designed to help you not to become a Python programmers but to learn its basics and enable you to expand your data science skills using it as a modern programming language.

## Course structure

Our goal here is not to provide a deep insight into Python and act as an official reference since you can easily can access hundreds of online sources to learn about each and every detail of Python.
Given the wide range of students' backgrounds, there is no assumption about prior knowledge about programming or data analysis. We've tried to provide you with simple examples which give you a clear understanding of functionality of different tools. There are also parts called **YOUR TURN** which ask you to put into practice what you have learned during the lesson. These parts are accompanied by three different symbols which show the difficulty of the exercise:

<img src="Images/baby.svg"   width="30" align="left">               

**EASY:** You're expected to solve it by yourself. (max 2 min)

<img src="Images/student.svg"   width="30" align="left">               

**So-So:** In case you find it hard to solve, try to ask your friend's opinion. (max 5 min)

<img src="Images/wizard.svg"   width="40" align="left">               

**HARD:** If you're not comfortable with it, leave it alone! once in home, try to attack it again!

For the questions that you should write code, you'll find a code block with a Python in it! just remove it and insert your answer instead.

<img src="Images/python.png"   width="300" align="left">               


While major parts of codes are self-explanatory, there are ones that need a more detailed explanation. These parts are indicated by an owl sign!

<img src="Images/owl.svg"   width="40" align="left">               

## Prerequisite

The only prerequisites for using this course is high-school level math and a running version of Python and Jupyter notebook.

# What is a programming language?

Simply put, a programming language is a intermediary language(with its predefined structure) which is able to translate human language(instructions) to a language which is understandable by a computer(Hardware).
There are different levels of programming languages with different scopes which we won't explain here in depth. In the following figure you can see the hierarchy of these languages and the interactions they have with each other.
<img src="Images/languages.jpg"  width="600" align="center">
[image source](https://www.informationq.com/computer-language-and-its-types/computer-language-and-its-types/)

Unlike languages like C and C++, Python is a interpreted language which means you can run it only you have the interpreter on your machine(installing Ptyhon = installing Python interpreter). In this [link](https://www.html.it/pag/15387/programma-compilato-e-interpretato/) you can learn about the differences between interpreted and compiled languages.

# What is an algorithm?

An algorithm is a series of instructions with a specific order and a defined end, used to solve a  specific problem. As an example, imagine you want to tell someone how to get to Milano Garibaldi from Bicocca University. You can write down the steps: (Notice how important is the order of steps)
- Look at the train information board
- Find out when and when is the next train to greco Pirelli station
- Go to the platform
- Get in the train
- Wait until you arrive to the greco Pirelli station
- Get off of the train
- ...

In this example, we are giving this instruction to a human being so we can simply use Italian language(or any other *natural* language) but what happens when we want a computer to follow our instructions? That's where computer languages come into the scene.

# Why Python?

Python is the principal (but not the only) programming language of BIBDA master. The reason behind this choice is mainly based on its strong characteristics like (but not limited to):
- Simple and minimalistic syntax 
- High efficiency
- Productivity and speed
- Extensive libraries
- Strong community support
- Acceptance by giants like Google and Facebook

Another point that makes Python an intresting programming language is its incredible growth in the European job market and computer/data science community:

<img src="Images/python_trend.png" width="700">

<img src="Images/py_growth.png" width="700">

[image source](https://stackoverflow.blog/2017/09/06/incredible-growth-python/)

# Running a Python code

In the previous parts we have seen together why we need a programming language and why we choose Python. Now let's briefly explore the different ways we can "run" our codes (algorithms) written in Python. There are four main ways:

- Running Python directly in command line/ bash
- Using an IDE (Ex. [IDLE](https://docs.python.org/3/library/idle.html), [PyCharm](https://www.jetbrains.com/pycharm/) and [Spyder](https://www.spyder-ide.org/))
- Using a Text Editor (Ex. [VsCode](https://code.visualstudio.com/), [Sublime Text](https://www.sublimetext.com/) and [Atom](https://atom.io/))
- Using a Notebook (Ex. [Jupyter](https://jupyter.org/), [nteract](https://nteract.io/) and [Zeppelin](https://zeppelin.apache.org/))

We can't describe each option in details here but if you are interested to now more about these tools and how they are different from each other, take a look at the [article](https://medium.com/@navid.nobani/adding-python-to-your-life-choices-everywhere-35bbf435fe5d) I've written about this subject.

Here as you may have noticed(!) we're are going to use Jupyter notebook for the rest of out course.
Jupyter notebook has an interesting developement story which you can find out more about it in [this article](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook).

## Using an IDE

# Use Python as a calculator

The most basic (and inefficient) use of any programming language is using it as a calculator! Let's see some examples:

$\frac{((119 + 0.789)^{3.14}\times 1000000000}{57^{\frac{5}{2.4}}} = 738170310705.7557$

In [7]:
(((119 + 0.789)**3.14) * 1_000_00000_0) / 57**(5/2.4)

738170310705.7557

There are also some interesting (and still extremely simple) calculation we can perform too:

In [5]:
989 % 5

4

In [73]:
9470 / 11

860.9090909090909

In [13]:
9470 // 11

860

"%" and "//" (Floor Division) are two of operators available in Python. Take a look at the [complete list of operations](https://docs.python.org/3.4/library/operator.html#mapping-operators-to-functions) in the Python documentation. The following table summarize the most important ones:

<img src="Images/operations.png">

<img src="Images/baby.svg"   width="30" align="left">               

**YOUR TURN :** compute the following :

$$(\frac{2019}{5})^{24} * 0.000314$$

In [8]:
((2019 / 5) ** 24) * 0.000314

1.1089735772993454e+59

# Variables

A variable is just a reference which points to a specific object in the memory. Imagine it as name tag which you attach to a piece of the memory of your computer. In this way everytime you need to access that pies you just need to follow the name tag. Obviously this attachment is not permanent, it means you can detach it and connect it to another piece of memory as in the same way, you can attach two different name tags to the same object.

<img src="Images/baby.svg"   width="30" align="left">               

**YOUR TURN :** We assign 12 to A, 2 to B and compute C by multiplication of A and B and assign the result to C. Now if we assign 3 to B, What would be the value of the C?

<img src="Images/variable.png" width="600" align="left">

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

Unlike C and Java which are "Statically-typed languages", Python is a "dynamically-typed language", which means variables must not only have a single data type, instead you can assign different objects with different data types to the variable (not simultaneously). You can read more about this subject [here](https://wiki.python.org/moin/Why%20is%20Python%20a%20dynamic%20language%20and%20also%20a%20strongly%20typed%20language).

Let's define a variable and assign a number to it: 

In [16]:
my_var = 10

We just created our first variable! let's print it to confirm what is inside:

In [17]:
print(my_var)

10


Now let's assign a text to **my_var**:

In [18]:
my_var = 'my fancy text'
print(my_var)

my fancy text


Notice that in the code above, we didn't explicitly tell Python which data type we're going to assign to "my_var".

## Variable naming

There are 3 rules you should have in mind when defining a new variable:
- It CAN contain only letters, numbers and underscore(\_).
- It MUST start either with a letter or underscore(\_). It CAN'T start with a number.
- It CAN'T/SHOULDN'T be a [reserved](https://docs.python.org/2.5/ref/keywords.html) name.

Let's explain a bit the last point. I used **CAN'T/SHOULDN'T** and not **CAN'T** because While you **CAN'T**  assign a value to some of these reserved key words (like **for**) actually if you want, you **CAN** assign a value to some of them (like function **print**); The point is even if you **CAN** do so, it's almost always absolutely a bad idea !

<img src="Images/baby.svg"   width="30" align="left">               

**YOUR TURN :** What would be the result? (answer without running it!)

print = 2

print(10)

- 2
- 10
- 20
- None of above

A variable name doesn't have any length limitation but it's better if you keep it as short as possible ( as long as it's easy to remember and reuse= being informative)

**Correct Examples:**
- myVal
- My_val
- ppppppppppppppppppppppp
- \_size_1

**Good Examples:**
- length
- size_before_trim
- item_1

**Wrong Examples:**
- 1_myval
- 49param

**bad Examples:**
- pp
- abc
- size_before_removing_outliers_from_main_table

[more details about variables](https://realpython.com/python-variables/)

<img src="Images/baby.svg"   width="30" align="left">               

**YOUR TURN :** Define three variables : **birth_year**, **birth_month** and **birth_day** and assign them your birth date.

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

# Data types

In Python , everything is an object and every object has a type. There are different ways to divide data types. For example You can divide them into *Scalers* which you can't sub-divide to further pieces(like a number) and non-scalers which you can sub-divide (like a list of numbers).

Another way to categorize them is based on their origin:

- Built-in Data Types
- Data types that are not built into the interpreter

Here we mainly talk about the built-in data types which can be divided into the following types:

<img src="Images/data_types.jpeg">

Notice that this isn’t how [Python documentation](https://docs.python.org/2/library/stdtypes.html) divides data types but in my opinion the official documentation may seem a bit confusing for a reader which is facing this argument for the first time.

## Numeric Types


The easiest data type to work with are “Numbers” category, since all of us has a good grasp of it and already know what we should expect to see when someone talks about numbers!

Two main sub-types of numbers which we see together are:

- Integers
- Floats

(Two other numeric sub-types are long and complex which we won’t discuss here)

### Integers

Integers are numbers without decimal points:

In [7]:
1 + 1

2

In [13]:
type(1 + 1)

int

In [8]:
1256

1256

In [14]:
34572765 * 6779_625_6_45

234390404212558425

You can easily check if a number is integer or not. The only thing you need to do is use **_type( )_** built-in function (more on built-in functions later) . The result should be **_int_** as you see below:

In [10]:
type(452347)

int

In [14]:
type(1_456_099)

int

### Floats

In Python language numbers with decimal are known as Floats:

In [12]:
3.14159

3.14159

In [16]:
type('I am not a cat')

str

In [14]:
type(768.90)

float

### Integer and Float operations

Let's do some basic arithmatic and see the result data types:

In [23]:
a = 1_869 + 67.34
print(a)
print(type(a))

1936.34
<class 'float'>


In [22]:
a = 1 * 67.34
print(a)
print(type(a))

67.34
<class 'float'>


In [19]:
a = 12.5 + 10.5
print(a)
print(type(a))

23.0
<class 'float'>


In [21]:
a = 12. / 2
print(a)
print(type(a))

6.0
<class 'float'>


To summarize:
- **int** (+ or - or \*) **int** = **int**
- **float** (+ or - or \*) **float** = **float**
- **int** / **int** = **float**
- **int** / **float** = **float**
- **float** / **float** = **float**

### Integer and Float conversion (Cast)

Using **_float( )_** and **_int( )_** we can convert integers to floats and vice versa:

In [27]:
print(int(45.89)) # convert float to int
print(int('347')) # convert string to int

45
347


In [ ]:
"""if you want to convert a string to int, the string MUST have
the form of an integer"""
print(int('56.76')) # this one doesn't work!

In [30]:
print(int(float('56.76'))) # this one does, why?

56


In [32]:
# The same thing is not true for converting string to float.
# it means the conversion works even if the string doesn't have the form of a 
# float
float('4')

4.0

<img src="Images/student.svg"   width="30" align="left">               

**YOUR TURN :** Considering **a = 3.14**, which code results in 3 ?

- A : floor(a)
- B: float(int(a))
- C : int(10 // a)
- D : None of above

## Strings

Strings can hold almost anything in character form, including text, symbols, and digits.

As an example let's take a look at a list (more on lists later) with 7 strings inside:

In [ ]:
['a simple text',
"R3a11ySm4rTP@$swo0rD",
'navidnobani',
'1366',
'7945-1414 box',
"cane",
"""I really hate these 
        !@$&ing trains"""]

Roughly, we can define strings as : everything that comes between ' ', " " or """ """. (Remember that this is a simplistic definition and not the whole story!). You may ask why we need to have three different ways to create a string? that's a good question! While no matter which you use, the outcome is always the same string object (For example for python 'cane', "cane" and """cane""" are exactly the same), there are certain situations which you should use them wisely. Suppose we want to create the following string:

> **I can't go to work today**

let's try to use " " first:

In [20]:
"I can't go to work today" # works perfectly!

"I can't go to work today"

and now """ """:

In [21]:
"""I can't go to work today""" # another success! :D

"I can't go to work today"

and finally   ' '  :

In [22]:
'I can't go to work today'

SyntaxError: invalid syntax (<ipython-input-22-62eb89c1839b>, line 1)

Wait, what is **invalid syntax** now! We get such an error when Python thinks what you have written doesn't make sense! To understand better what is a **Syntax Error** let's see an example of natural language:
- This is a correct sentence $\rightarrow $ *Marco easts sandwich* $\rightarrow $ (noun) (verb) (noun)
- This is a **Syntactically wrong** sentence $\rightarrow $ *Marco cat sandwich* $\rightarrow $ (noun) (noun) (noun)

So does it mean any (noun) (verb) (noun) gives us a correct combination? Yes and No! Yes because (noun) (verb) (noun) is a **Syntactically correct** sentence but it might still be meaningless $\rightarrow $ Marco listens sandwich ( It has a **static semantic error** )

The same thing exists in Python:
- *'Seven'11* is Syntactically wrong because Python can't  understand what do you mean by (str)(int) $\rightarrow $ **SyntaxError**

- *'seven' * 'two'* is also wrong but not Syntactically because although Python can understand what is your goal, (multiplying two strings) it can't do it $\rightarrow $ **TypeError**


Back to our exampole in the last cell, can you figure out what is the problem? (of course you can!)
There are two solutions here:
- using alternative strings as we did before (' ' or " " )
- using a character scape : In Python (and other programming languages) certain characters has a reserved role. It means not all the characters for python have the same characteristic behind the scene. In order to force Python to ignore the special role of certain characters like **\'** or **\"** we can use a backslash :

In [27]:
'I can\'t go to work today'

"I can't go to work today"

Now let's try to write a multi-line string :

In [28]:
'some
thing
long'

SyntaxError: EOL while scanning string literal (<ipython-input-28-d14d2b016c36>, line 1)

In [29]:
"some
thing
long"

SyntaxError: EOL while scanning string literal (<ipython-input-29-3044f7f10f02>, line 1)

In [31]:
"""some
thing
long"""

'some\nthing\nlong'

Well' it seems working but what are those weird **\n** s in the middle? **\n** is one of the [Python literals](https://docs.python.org/2.0/ref/strings.html) that is used to indicated a new line. We don't go into details here but remember what we have said before about the characters with special meaning and how sometimes we need to escape them. As the last example let's try to make a string of the current notebook's path:

**C:\Documents\Newsletters\Summer2018.pdf**

In [18]:
'C:\Documents\Newsletters\Summer2018.pdf'

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 12-13: malformed \N character escape (<ipython-input-18-fec08ede76cf>, line 1)

As you can see we're getting a SyntaxError again. The reason is that Python thinks we want to use \n but we wrote \N instead. Since our goal here is not to indicate a new line (\n) but to use **\\** as part of string, we need to escape this special character. How can we do it?

By using **\\** itself! When Python sees **\\** is understands that you don't want to use special meaning of **\\** but you actually need to use backslash itself:

In [40]:
'C:\Documents\\Newsletters\Summer2018.pdf'

'C:\\Documents\\Newsletters\\Summer2018.pdf'

Before going to the next part which is about string operations, let's do  quick recap about what we have seen before. As you remember we've said that we can convert floats to integers (cast them) and vice versa and also a string to float or integer. The same thing exists in the contrary way: we can convert integers and floats to strings:

In [1]:
customer_id = 73456
print(customer_id)
print(type(customer_id))

73456
<class 'int'>


In [2]:
customer_id_str = str(customer_id)
print(customer_id_str)
print(type(customer_id_str))

73456
<class 'str'>


### Common string operations

Having a string, you can apply on it a wide variety of string methods in order to modify it. There are dozens of operations which you can find [here](https://docs.python.org/2/library/string.html). We'll see together the mostly used ones:

#### Split

Returns a list of pieces of original string cut on the indicated string.

In [49]:
text = 'This is a Python course'
print(text)
text = text.split(sep=' ')
print(text)

This is a Python course
['This', 'is', 'a', 'Python', 'course']


In [23]:
text = 'I saw the guy, and suddenly he disappeared'
print(text)
text = text.split() # notice that I wrote ',' instead of sep=','
print(text)

I saw the guy, and suddenly he disappeared
['I', 'saw', 'the', 'guy,', 'and', 'suddenly', 'he', 'disappeared']


#### Slicing

Cutting the string in a way to have new string which is the subset of the original string.

Actually, before explaining slicing, we need to learn a principal concept in Python : Indexing.
Suppose you have a box with 11 pens in it. If you want to take out them one by one and count them, most probably you'll go with:
- One
- Two
- ...
- Eleven

It means, you're using a 1-based index, you indicate the first item with number 1. Python on the other hand, uses a 0-based index. It means it refers to the first object as number(index) 0. So to count the pens in our example, Python goes:
- Zero
- One
- ...
- ten

Ok, now that we know how Python indexing works, we can see string indexing.
In Python Indexing/slicing is not limited to strings, instead, we can slice/index any object that can be considered as a group of objects. That being said, It should be clear now that for example the string: "cane" while considered as a string object is also seen as a container(not as a technical definition) of "c", "a", "n" and "e" with indexes 0, 1, 2 and 3. It means we can slice this string using their indexes. Let's see an example:

suppose we have this string: "NEW YORK" and we want to get the first 3 letters. The indexes are show below:

<img src="Images/slice.png" width="500">



In [27]:
text[40:80]

''

In [25]:
text = 'NEW YORK'
print(text[1]) # E: second letter

print(text[0:3]) # NEW
print(text[40:80]) # YORK

print(text[:3]) # NEW
print(text[4:]) # YORK

E
NEW

NEW
YORK


Indexes can be address not only from the beginning but also from the end:

<img src="Images/slice_2.png" width="500"> 

In [20]:
text = 'NEW YORK'
print(text[-7]) # E: second letter

print(text[-8:-5]) # NEW
print(text[-4:]) # YORK

print(text[:-5]) # NEW
print(text[-4:]) # YORK

E
NEW

NEW
YORK


Slicing has other options which give you more control. We won't cover them here but in this [site](https://www.pythoncentral.io/cutting-and-slicing-strings-in-python/) you can find some interesting examples.

#### Replace

Returns a new version of the original string in which the str_to_be_replaced instances are replaced with str_to_be_replaced_with:

In [47]:
text = 'I love my dog'
print(text.replace('dog', 'cat'))

I love my cat


#### Concatenation

concatenation allows you to create new strings but concatenating existing string together , using "+":

In [37]:
text_1 = 'Hello'
text_2 = 'World!'
text_3 = text_1 + ' ' + text_2

print(text_3)

Hello World!


#### Strip

Removes the given string from the beginning and end of the original string. Note: Like split( ) function, the default value of strip( ) function is space so if you run my_text.strip( ), it cleans my_text string from starting and ending spaces.

In [27]:
text_1 = ' Pirelli Spa '
print(text_1.strip())

text_2 = 'Continental -'
print(text_2.strip('-').strip())

text_3 = '*Python***'
print(text_3.lstrip('*')) # There is also "rsplit"

Pirelli Spa
Continental 
Python***


Although not string operations, **print** and **len** function are Python built-in functions (more on this later) which can be used with different data types like strings, numbers, lists,...

#### Printing a string

**print** function prints(!) the input to the stdout(standard output). Note that not all the Python objects can be printed out.

In [42]:
print('something')
print('-'*40)

text = 'just a short text'
print(text)
print('-'*40)

text_1 = 'My name is'
text_2 = 'Navid'
print(text_1, text_2)
print('-'*40)

text_3 = 'University'
text_4 = 'of'
text_5 = 'Bicocca'
print(text_3, text_4, text_5)
print('-'*40)

text_6 = 'folder1'
text_7 = 'folder2'
text_8 = 'folder3'
text_9 = 'file'
print(text_6, text_7, text_8, text_9, sep='/')

something
----------------------------------------
just a short text
----------------------------------------
My name is Navid
----------------------------------------
University of Bicocca
----------------------------------------
folder1/folder2/folder3/file


#### String  length

**len** returns the number of characters in the given string:

In [48]:
print(len('bicocca'))
print(len('AC DC!'))
print(len(' cane 1'))

7
6
7


<img src="Images/baby.svg"   width="30" align="left">               

**YOUR TURN :** Replace the spaces in the **target** with the 10th character of the **source**:

In [45]:
char_10 = source[9]
target.replace(' ', char_10)

'pPHpPHpPHsSHsSHsSHcCHcCHcC'

In [44]:
source = '\'\'\'ChUpAcHuPs"/"/"/"'
target = 'pP pP pP sS sS sS cC cC cC'

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

#### Other operations

There are some operations that perform a transformation on strings:

In [46]:
text = 'MilaN'
print(text.lower())
print(text.upper())
print(text.title())

milan
MILAN
Milan


Being a strongly typed language, Python doesn't let you to use operations on objects unrelated to them. For example "'Cat' + 3" gives you a "TypeError" since addition operation is for numerical objects not strings:

In [31]:
'cat' - 3

TypeError: unsupported operand type(s) for -: 'str' and 'int'

But at the same time, there are some exceptions. For example "'cat' * 3" works since Python assume that you want to repeat the string 'cat' , 3 times:

In [33]:
'cat' * 3

'catcatcat'

## Booleans

Booleans are are another core data type of Python which consist of only two values: **True** and **False**. Boolean values are mainly used when we're somehow comparing different values together. (More on comparisons later).
In Python True has a value of 1 while False's value is 0. We can check this fact by converting them to integer:

In [39]:
print(int(True))
print(int(False))

1
0


## Lists

Lists are one of the most common sequence objects in Python which provide a collection of arbitrary type objects. Lists have several characteristics, like:
- List can contain objects with different data types in the same time.
- They are mutable.
- There is no limit for their length.

In [52]:
list_A = [1, 'A', 234, 'BATMAN']
list_B = ['Na',' Nana', 'Nanana']
list_C = [134.05, 87.13, 109, 13.14, 530000, 19]

let's use some of functions we have used with Strings, this time with lists:

In [56]:
print(list_A) # print
print(len(list_B)) # len
print(list_C[3]) # slice : asking for just one item
print(list_A[1:3]) # we're asking two items so the result will be a list
print(list_B[:])

[1, 'A', 234, 'BATMAN']
3
13.14
['A', 234]
['Na', ' Nana', 'Nanana']


Just like Strings, we can concatenate lists together:

In [84]:
[1, 'ABC'] + [1.0, [4, 98, 11.567]]
# the same result can be achieved by using the following :
# [1, 'ABC'].extend([1.0, [4, 98, 11.567]])

[1, 'ABC', 1.0, [4, 98, 11.567]]

Using **append** method we can add new items to the end of a list:

In [67]:
my_list = ['A', 'B', 'C']
word = 'D'
my_list.append(word)
print(my_list)

['A', 'B', 'C', 'D']


While append adds the new item at the end of the list, using **insert** you can insert the item in any inex you want:

In [51]:
my_list = ['a', 'bar', 'foo']
my_list.insert(-1, 'ham') # it's equal to my_list.append('ham')
print(my_list)

['a', 'bar', 'ham', 'foo']


In [55]:
small = [4, 5, 1, 9]
print(small)
small.sort(reverse=True) # Note that sort is an in-place function
print(small)
small.sort(reverse=False)
print(small)

print('-'*30)

# unlike sort(), sorted creates a new copy of the list and doesn't change 
# the original list
original = [4, 9, 1, 8, 0]
print(original)
print(sorted(original))
print(original)

[4, 5, 1, 9]
[9, 5, 4, 1]
[1, 4, 5, 9]
------------------------------
[4, 9, 1, 8, 0]
[0, 1, 4, 8, 9]
[4, 9, 1, 8, 0]


**remove**, **pop** and **del** are used to remove an item from a list:

In [56]:
# remove

list_1 = ['A', 'B', 'C', 'A', 'D', 'A']
list_1.remove('A')
print(list_1)

['B', 'C', 'A', 'D', 'A']


In [80]:
# pop

list_2 = [1, 2, 3, 4, 5, 6]
list_2.pop(2)
print(list_2)

list_2 = [1, 2, 3, 4, 5, 6]
list_2.pop()
print(list_2)

[1, 2, 4, 5, 6]
[1, 2, 3, 4, 5]


In [82]:
# del

list_2 = [1, 2, 3, 4, 5, 6]
del list_2[2]
print(list_2)

list_2 = [1, 2, 3, 4, 5, 6]
del list_2[3:]
print(list_2)

[1, 2, 4, 5, 6]
[1, 2, 3]


Lists are mutable, it means we can change their contents in-place:

In [105]:
some_list = ['spam', 'ham', 'car', 'foo']
some_list[2] = 'bar'
print(some_list)

['spam', 'ham', 'bar', 'foo']


As the last thing, let's see how can we check if an item is in a list or not:

In [40]:
target_1 = 11
my_vals = [1, 56, 876, 32, 11, 6, 9]

print(target_1 in my_vals)

True


It may seems useless since you can easily see if a certain value exists in a list but remember that not always deal with small lists which you can simply visualize. 

By using **not in** instead of **in** we can check if an item doesn't exists in a list:

In [42]:
target_2 = 32
print(target_2 not in my_vals)

False


<img src="Images/student.svg"   width="30" align="left">               

**YOUR TURN :** Using slicing, get the letter **x** from final_list :

In [67]:
my_list = [1, 4, 8, 'foo']
your_list = ['ham', '1', 2, 6]
his_list = ['4', '2', 'xyz', '6']


print(f'Original : {my_list}')
my_list[-2] = your_list

print(f'First change : {my_list}')
my_list[-2][-1] = his_list

print(f'Second change : {my_list}')
final_list = my_list

Original : [1, 4, 8, 'foo']
First change : [1, 4, ['ham', '1', 2, 6], 'foo']
Second change : [1, 4, ['ham', '1', 2, ['4', '2', 'xyz', '6']], 'foo']


In [66]:
final_list[2][3][2][0]

'x'

## Dictionaries

Dictionaries, Like a lists, are built-in sequence objects which can contain different data types. The main difference between lists and dictionaries is that unlike lists, dictionaries are not ordered collection of items, and as a result you can access their contents using indexes and positions. Instead dictionaries can be accessed using a key:value method.

In [108]:
dict_1 = {'A': 1, 'B': 3, 'D': 'X'}
print(dict_1['D'])

X


Adding items to a dictionary is easy. Just remember that you can't just add a value like, 10, but you also need to add a key:value pair:

In [68]:
shirt = {'color': 'red', 'size': 'M', 'quantity': 15}

In [69]:
shirt['quantity']

15

In [117]:
shirt['price'] = 45
print(shirt)

{'color': 'red', 'size': 'M', 'quantity': 15, 'price': 45}


Create a dictionary with your **name, age, city**

In [70]:
new_dict = {'name' : 'Navid', 'age': 31, 'city': 'Milan'}

In [71]:
print(new_dict)

{'name': 'Navid', 'age': 31, 'city': 'Milan'}


In the same way you can remove a key:value pair:

In [121]:
del shirt['size']
print(shirt)

{'color': 'red', 'quantity': 15, 'price': 45}


Some useful methods:

In [123]:
print(shirt.keys())
print(shirt.values())

dict_keys(['color', 'quantity', 'price'])
dict_values(['red', 15, 45])


## Tuples

Tuples are very similar to lists but unlike lists, are not mutable. It means you can't modify them in-place as you can do with lists. (But still you can access their contents using indexes):

In [125]:
my_tuple = (1, 3, 'foo')
print(my_tuple[2])

foo


In [126]:
my_tuple[0] = 'ham'

TypeError: 'tuple' object does not support item assignment

## Files

Technically speaking files are categorized as one of the core python data types (like strings, lists,...) while actually they are external objects saved on your machine which are imported to Python using python built-in functions like **open**. Python, either using built-in function or external libraries is able to read from and write to a wide range of files. Here we'll going to see three commonly used files: *.txt , .csv* and *.json* files.

### Text files

In [73]:
# creating a new file and writing to it
file = open('first_text_file.txt', 'w')
file.write('Navid Nobani')
file.close()

In [74]:
# openning an existing file and writing to it
file = open('first_text_file.txt', 'a')
file.write('\nanother line!')
file.close()

In [77]:
# openning an existing file and reading from it
file = open('first_text_file.txt', 'r')
line = file.readline()
print(line)
file.close()

Hello World!



As you have noticed, in order to read from/write to a file, we do these steps:
- open/create a file
- read from/write to it
- close the file

Just like opening and actions you do on the file, closing it is absolutely important since having an open instance uses your RAM and slows down your script. Actually there is a better way to manage opening and closing files which is using content managers. Given our limited time we can't go in details here but fortunately using them is easy. Look at the following example:

In [79]:
with open('first_text_file.txt', 'w') as file:
    file.write('Some funny text :D')

This is equal to the following code:

In [80]:
# creating a new file and writing to it
file = open('second_text_file.txt', 'w')
file.write('Some funny text :D')
file.close()

### CSV Files

There are two main ways to open a csv file: 
- using [csv module](https://docs.python.org/3/library/csv.html) ( which comes with python)
- or using [pandas library](https://pandas.pydata.org/) (which you should install it first)

*[This site](https://realpython.com/python-csv/) has a rich explanation about csv files in Python.*

first let's take a look at csv library:

In [75]:
import csv # NEW STUFF !

with open('./files/data/camdenhousesales15.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader: # NEW STUFF !
        print(row)

FileNotFoundError: [Errno 2] No such file or directory: './files/data/camdenhousesales15.csv'

For working with csv files (specially the big ones!) I personally prefer pandas library over csv module. Later in the course we'll briefly learn about pandas but let's have a sneak peek now!

In [87]:
import pandas as pd

df = pd.read_csv('./files/data/camdenhousesales15.csv')
df

UID     Price             Date              Street District  \
0  597034  22500000  06/12/2015 0:00         AVENUE ROAD   CAMDEN   
1  594622  15200000  11/04/2015 0:00   GREENAWAY GARDENS   CAMDEN   
2  594696  13500000  03/10/2015 0:00   TEMPLEWOOD AVENUE   CAMDEN   
3  594592  10500000  09/14/2015 0:00          CHURCH ROW   CAMDEN   
4  515677   8950000  10/30/2015 0:00           THE GROVE   CAMDEN   
5  592992   8750000  09/01/2015 0:00  ST GEORGES TERRACE   CAMDEN   
6  592670   8500000  11/12/2015 0:00     CHESTER TERRACE   CAMDEN   
7  594265   8300000  08/19/2015 0:00        BELSIZE PARK   CAMDEN   
8  594623   8000000  02/13/2015 0:00   GREENAWAY GARDENS   CAMDEN   

           Region Postcode  oseast1m  osnrth1m  
0  GREATER LONDON   NW86HS    527076    183790  
1  GREATER LONDON   NW37DJ    525813    185524  
2  GREATER LONDON   NW37XA    525779    186084  
3  GREATER LONDON   NW36UU    526159    185603  
4  GREATER LONDON    N66JU    528177    187307  
5  GREATER LONDON   NW18XH    527818    184013  
6  GREATER LONDON   NW14ND    528756    182768  
7  GREATER LONDON   NW34EE    526693    184611  
8  GREATER LONDON   NW37DJ    525813    185524

The table you see in the previous cell is a "DataFrame" one of the most important non-core data types you'll use in data science field. We'll learn more about dataframes later in the course.

# Functions

Python functions are a bundle of code that perform a specific functionality if this functionality is going to be reused later in another part of the code. 

Suppose we want to perform some simple statistics on a list of numbers:

In [55]:
import numpy as np
np.random.seed(42)

data = np.random.rand(1,100_000).tolist()[0]
std = np.std(data)
mean = np.mean(data)
median = np.median(data)
min_val = min(data)
max_val = max(data)
for val in [std, mean, median, min_val, max_val]:
    print(val)

0.2883400052995804
0.49948825007353703
0.5006297820093312
5.536675737993768e-06
0.999992042302966


Ok, we did it! but what if we now want to repeat these processes for another list of numbers. We have two options:
    
- Updating the data variable with a new list
- Re-write all the steps for another list

Both these solutions are bad! or at least not Pythonic. The correct way to deal with such a task is to pack them as a function.

## Built-in functions

Until this point, we have many functions without knowing the exact definition of a function! We've seen:

- print
- len
- max
- min

These are just few example of hundreds of functions that are part of core python language (it means to use them you don't need to import any library/package). A function always has the following structure:

<img src="Images/function.png" width="500"> 

Parameters are inputs that functions may or may not need in order to perform their desired tasks. For example lats take a look at **print** function which take a string as input and prints it.

In [25]:
print('My shiny text!')
print() # prints an empty line
print('X', 'Y', 'Z', sep='+++', end='\n')
print('X', 'Y', 'Z', '+++', '°°°')

My shiny text!

X+++Y+++Z
X Y Z +++ °°°


you can see that print accepts zero , one or (technically) infinite number of parameters. Let's see another built-in function : **map**

**map** returns a special iterable with type "map":

In [42]:
my_list = ['-1.567', '0.2', '-65']
list(map(float, my_list))

[-1.567, 0.2, -65.0]

map takes either no parameter and returns an empty list or takes two or more parameters.(let's say the function we want to apply and the iterable we want to apply function to). It means it won't work with just one parameter(function or iterable) and we will get a "TypeError" message.

<img src="Images/student.svg"   width="30" align="left">               

**YOUR TURN :** using **map** and **abs** functions, create a list with the absolute value of the list's items.

In [76]:
new_list = [-1, 5.5, -9, -123, 65]
list(map(abs, new_list))

[1, 5.5, 9, 123, 65]

## Custom functions

Although there are numerous built-in and third-party modules and packages ready to be used by you, there are some tasks that are too specific which you can't find any existing module/function to do that task for you. In these cases ( which happen a lot) we need to write our own functions.
Consider the initial example we saw at the beginning of the "functions", calculating some simple statistics.

In [85]:
def simple_stat(data, log=True):
    """Calculating simple statistics of a given list.
    
    For the the given list of numbers, calculates standard deviation, 
    Mean, Median, Minimum and Maximum statistics.

    Args:
        data : A list of numerical data.
        log: If True, prints a simple report.
        
    Returns:
        Return a list of the given numbers
    """
    std = np.std(data)
    mean = np.mean(data)
    median = np.median(data)
    min_val = min(data)
    max_val = max(data)
    
    vals = [std, mean, median, min_val, max_val]
    names = ['Standard deviation', 'Mean', 'Median', 'Min', 'Max']
    
    if log:
        for name, val in zip(names, vals):
            print(f'{name} : {val}')
            #print(f'{name} : {round(val, 2)}')
    return vals

In [79]:
def simple_stat(data):
    
    std = np.std(data)
    mean = np.mean(data)
    median = np.median(data)
    min_val = min(data)
    max_val = max(data)
    
    vals = [std, mean, median, min_val, max_val]
    names = ['Standard deviation', 'Mean', 'Median', 'Min', 'Max']
    
    for name, val in zip(names, vals):
        print(f'{name} : {val}')
    return vals

In [81]:
import numpy as np

In [86]:
np.random.seed(42)

data = np.random.rand(1,100_000).tolist()[0]
results = simple_stat(data)

Standard deviation : 0.29
Mean : 0.5
Median : 0.5
Min : 0.0
Max : 1.0


Following figure shows the structure of a custom function:

<img src="Images/function_detail.png" width="900"> 

<img src="Images/student.svg"   width="30" align="left">               

**YOUR TURN :** 

- Using **round** function, modify the *simple_stat* in a way that returns the 2-digit rounded values.
- Add *range* statistics to results

In [84]:
round(134.456435453, 4)

134.4564

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

## Lambda functions

Lambda functions are smaller and simpler version of normal function which come handy when we use **functional programming** features of Python. Providing a technical definition of functional programming is way beyond scope of our mini-course but in a nutshell, it means using functions as arguments of other functions. 
Let's first see the example of map function we saw:

In [58]:
my_list = ['-1.567', '0.2', '-65']
list(map(float, my_list))

[-1.567, 0.2, -65.0]

Now suppose that on top of changing the data types from str to float, we want to add 100 to each of them. remember how map function . works? It applies the first argument you give to it (in this case, float) to the sequence you pass as the second argument (in our example: my_list). So it's clear that we need to somehow change float to *something* that also adds 100 to each item. This *something* either should be *type* or a *function*. Ok, based on whjat we have learned until this point, create a custom function which does what we want:

In [59]:
def float_plus_100(number):
    """Converts the given number to float and adds 100 to it
    
    args:
        number : int or float
        
    returns:
        float
    """
    return float(number) + 100

Ok, our function is ready. Let's test it:

In [60]:
float_plus_100('3.14')

103.14

It works! Now we can add it to our map function:

In [61]:
list(map(float_plus_100, my_list))

[98.433, 100.2, 35.0]

We did it! The only problem is in order to perform such a simple task we had to write a function, which most probably we're not going to use it again! That's why lambda functions exist! Let's re-write or code using lambda:

In [62]:
list(map(lambda x : float(x)+100, my_list))

[98.433, 100.2, 35.0]

As you can see, we did the same thing without defining any function. In the following figure you can see the comparison between a lambda function and its corespondent function:

<img src="Images/lambda.png" width="800"> 

Such a comparison may indicate that lambda functions are the definite choice but in reality, we use functions way more than we use lambdas since dealing with real data, often we should perform tasks that are too complex to be written as a lambda function.

# Control Flow

Until now, we've works with single items. for example we sliced a string, or write a file. But what if we want to do something (perform an action) on a sequence of objects? The first type of loops we explore is for loops.

## For statement

Suppose that we have a list of our colleagues year of births and we want to calculate their ages, print them and put them in a new list called ages:

In [88]:
years = [1987, 1990, 1980, 1973]
ages = [] # creating an empty list

We know how to get a list's items using indexes. So what if we take each item and subtract it from 2019?

In [89]:
age_1 = 2019 - years[0]
print(age_1)
ages.append(age_1)

age_2 = 2019 - years[1]
print(age_2)
ages.append(age_2)

age_3 = 2019 - years[2]
print(age_3)
ages.append(age_3)

age_4 = 2019 - years[3]
print(age_4)
ages.append(age_4)

32
29
39
46


In [90]:
print(ages)

[32, 29, 39, 46]


Ok, we did what we've we asked for! but I think you agree that it wasn't quite efficient as we've written more than 12 lines of code to perform three simple operations on 4 items! imagine you want to calculate the age of all Bicocca employees! Fortunately we for repetitive tasks like this( when we are dealing with sequence objects like lists, tuples, dictionaries or strings) we can use loops. In this case we're going to use a for loop:

In [98]:
ages = []
for year in years:
    age = 2019 - year
    print(age)
    ages.append(age)

32
29
39
46


This is the general structure of a for loop:

<img src="Images/for_loop.png" width="500"> 

*Notice: for loops can have an "else" clause but we're not going to talk about them here*

<img src="Images/baby.svg"   width="30" align="left">               

**YOUR TURN**:
In the previous example, Why can't we define the empty list inside the loop instead of outside it?

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

## While statement

While loops has a similar objective as for loops but while for loops, in theory iterate through all the items in the provided sequence, a while loop goes forward until meeting a certain condition.
Suppose we want to print numbers between 0 and 10 and we want to do it using **while**.
Let's see the info we have from the question:

- we should print numbers
- numbers should be between 0 and 10

In [10]:
num = 0 # initial number is set to 0
while num <= 10: # while the number is less than or equal 10, continue
    print(num, end='-')
    num = num + 1 # adding one to the current value of the num = num+=1

0-1-2-3-4-5-6-7-8-9-10-

Just like any other thing, we can achieve the same result using different methods and functions. For example we can get the numbers we want by using a for loop:

In [12]:
for num in range(11): # what is range?
    print(num, end='\t')

0	1	2	3	4	5	6	7	8	9	10	

*Note: Just like for loops, while loops also can have a else clause*

Here is the general structure of a while loop:

<img src="Images/while_loop.png" width="500"> 

<img src="Images/student.svg"   width="30" align="left">               

**YOUR TURN**:
What if we use a condition which is always true?

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

## If statement

Often, you need to execute some statements only if some condition holds, or choose statements to execute depending on several mutually exclusive conditions. The Python compound statement if, which uses if, elif, and else clauses, lets you conditionally execute blocks of statements. Here’s the syntax for the if statement:

It's common that you want to execute a part of code if a certain condition holds (it's True). To do so in Python we use If statement. Let's go back to the simple example of printing numbers we've seen for while and for statements but this time suppose that you want to print the number only if it's an odd number:

In [3]:
num = 0 # initial number is set to 0
while num <= 20: # while the number is less than or equal 20, continue
    if num%2 != 0: # if the reminder of them with 2
        print(num)
    num = num + 1 # adding one to the current value of the num = num+=1

1
3
5
7
9
11
13
15
17
19


Ok, now let's use also *eles* and *elif* clauses. Imagine that you have a set of ages and you want to print one if the following labels based on the age:
- kid
- Teen
- adult
- old

In [91]:
ages = [56, 2, 14, 8, 33, 23, 19, 80, 6, 9, 27]

for age in ages:
    if age <= 12:
        print(age, 'Kid', sep=' - ')
    elif age <= 19 and age >= 13:
        print(age, 'Teen', sep=' - ')
    elif age <= 60 and age >= 20:
        print(f'{age} - Adult') # Did you noticed anything new here?
    else:
        print(age, 'Old', sep=' - ')

56 - Adult
2 - Kid
14 - Teen
8 - Kid
33 - Adult
23 - Adult
19 - Teen
80 - Old
6 - Kid
9 - Kid
27 - Adult


## Range function

Range is a simple and handy function which usually is used within a for loop(but not always). range function has three inputs:
    - start
    - end
    - step

In [94]:
for i in [0, 1, 2, 3]:
    print(i)

0
1
2
3


In [100]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [101]:
my_list = ['ABC', 'BVG', 'UHY', 'UQH', 'LLL']
for i in range(len(my_list)):
    print(my_list[i])

ABC
BVG
UHY
UQH
LLL


<img src="Images/wizard.svg"   width="30" align="left">               

**YOUR TURN**: using as for loop print items inside each key of the given dictionary and print numbers that are less than 10. (some numbers by mistake were recorded as a string, take care of them too!)

**Hint**: *You may want to use **.isnumeric( )** string method*

In [149]:
target = {'A': [1.0, 5 ,7, 'foo'], 
          'B': [4, [12], '3', 83]}

In [152]:
for key in target.keys():
    for item in target[key]:
        check = 0
        if type(item) in [int, float] :
            if item < 10 :
                check = 1
        elif type(item) == str:
            if item.isnumeric():
                if int(item) < 10 :
                    check = 1
        if check == 1:
            print(item)    

1.0
5
7
4
3


In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

## Break, Continue and pass clauses

Let's have a quick review of statements we have learned until now:
- **For statement** : repeats a task for a given sequence
- **While statement** : repeats a task while a given condition is True
- **If statement** : Evaluates a condition and acts upon the result

Looking at these statements it's clear that we can combine them to get a certain task done. For instance: For each item in this list check if condition 1 is True do action 1, otherwise do action 2:

In [106]:
salaries = [1000000, 5000, 11000]

for salary in salaries:
    if salary < 120_000:
        print(f'{salary:,} : Low')
    elif salary > 999_000:
        print(f'{salary:,} : High')
    else:
        print(f'{salary:,} : Normal')

1,000,000 : High
5,000 : Low
11,000 : Low


In the above example we used **for** and **if** together to examine each item and print a label based on the item's value. Well, It's not alway the case to go through every item of a sequence. Sometime we need to break the loop or continue to the next item without spending time with the current item. We can achive these types of action by using these clauses:

- continue
- break
- pass

Suppose you want to find the first number that is less than a specific number in any given list of numbers. You can create a function to do this using a for loop:

In [107]:
def find_number(data, limit):
    """Finds the first number in a given list which is less than the defined threshold
    
    Args:
        data : A list containing numerical values
        limit : Threshold defined by user
    
    Returns:
        The first number in the given list smaller than threshold
    """
    all_good = []
    for i in data:
        if i < limit:
            answer = i
            all_good.append(i)
    return all_good

Ok, let's test our function:

In [108]:
nums = [973, -1428, 315, -788, 1477, -428, -1187, 592, -108, 370]
limit = -500

print(find_number(nums, limit))

[-1428, -788, -1187]


Well, it kinda works...the problem is that it return the last number in the list that is less than -500 instead of the first one! (-1428)
Of course it's not because Python couldn't find the first number (-1428) but the problem is since we simply just used a for loop, after finding -1428 Python continued to examine other items in the list...something that we shouldn't have done. There are cases like this that we want to stop(break) the loop as soon as a certain condition is satisfied. We can write our function like this:


In [22]:
def find_number(data, limit):
    """Finds the first number in a given list which is less than the defined threshold
    
    Args:
        data : A list containing numerical values
        limit : Threshold defined by user
    
    Returns:
        The first number in the given list smaller than threshold
    """
    for i in data:
        if i < limit:
            answer = i
            break
    return answer

print(find_number(nums, limit))

-1428


And as you can see this time we get the right answer. In this simple case we could have achieve this also without using break and just by putting  return clause in a different place:

In [23]:
def find_number(data, limit):
    """Finds the first number in a given list which is less than the defined threshold
    
    Args:
        data : A list containing numerical values
        limit : Threshold defined by user
    
    Returns:
        The first number in the given list smaller than threshold
    """
    for i in data:
        if i < limit:
            answer = i
            return answer

print(find_number(nums, limit))

-1428


The reason that the function above give us the answer even without using break is that when Python reaches a **return** in a function, it exits immediately before continuing with the rest of code.
Let's do another example: Suppose you received 4 orders for a can of beer from 4 of your customers. In order to know if you can proceed with the order or not, you need to check 3 things: client having at least 18 years old, having at least 2 Euros in his bank card and be in a 3 kilometer radius from your shop. As you can see in the following cell, we can use continue clause after age check. In this way if the client has less than 18 years old, it's useless to check for the other conditions:

In [27]:
clients = {'2341': {'age': 15, 'name': 'Ale', 'balance': 658, 'distance': 11},
           '5682': {'age': 61, 'name': 'Ettore', 'balance': 890, 'distance': 1},
           '1873': {'age': 19, 'name': 'Tacca', 'balance': 121, 'distance': 5},
           '9950': {'age': 31, 'name': 'Navid', 'balance': 0, 'distance': 12}}

codes = list(clients.keys())

for code in codes:
    if clients[code]['age'] < 18:
        continue
    if clients[code]['balance'] >= 2 and clients[code]['distance'] < 3:
        print(f"{clients[code]['name']} can have a beer!")

Ettore can have a beer!


Now imagine that the shop manager tells you that he is thinking to do something for the clients that have all the conditions (age and credit) but are living in more distant neighbourhoods. The problem is that it's Fridays evening, you want to go home as soon as possible but he can't make his mind about how exactly he's going to handle the delivery situation. So you know you need to modify your function to reflect the new situation but you still don't know what would be the solution. So you can use a pass clause as a placeholder in your function:

In [29]:
clients = {'2341': {'age': 15, 'name': 'Ale', 'balance': 658, 'distance': 11},
           '5682': {'age': 61, 'name': 'Ettore', 'balance': 890, 'distance': 1},
           '1873': {'age': 19, 'name': 'Tacca', 'balance': 121, 'distance': 5},
           '9950': {'age': 31, 'name': 'Navid', 'balance': 0, 'distance': 12}}

codes = list(clients.keys())

for code in codes:
    if clients[code]['age'] < 18:
        continue
    if clients[code]['balance'] >= 2:
        if  clients[code]['distance'] < 3:
            print(f"{clients[code]['name']} can have a beer!")
        else:
            pass

Ettore can have a beer!


<img src="Images/wizard.svg"   width="30" align="left">               

**YOUR TURN**: Use **break** to write a function that calculates the sum of the first n items of the given number list.

In [69]:
def sum_n(data, n):
    num = 1
    summ = 0
    for i in data:
        if num > n:
            break
        summ += i
        num += 1
    return summ

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

## Comparisons operators

Comparison operators are not technically considered as a part of "Control flow" but since their usage with mentioned statements, I put them here. As the name suggest these operators **compare** two object and return either *True* or *False*. Let's see some examples:

In [4]:
a = 15.6
b = 79
print(a == b)
print(a != b)
print(a < b)
print(a > b)
print(a <= b)
print(a >= b)

False
True
True
False
True
False


# Importing libraries

reading csv files, we used :

In [8]:
import csv
import pandas as pd

The reason we did this is because like lots of other functionalities, reading csv files doesn't exist as a built-in function in Python language. Instead there are various libraries that has modules that are capable of performing those certain functions. To use these modules you need to import them in your code. This is exactly we've done in the csv section. 

The following figure shows the simplified structure of Python's modules:

<img src="Images/module.png" width="800">

There are different ways to import a package or a specific module of it:

Importing a library as a whole. For example the following code imports **re** package (regex) but not any module inside it specifically. It means for example if I want to use one of its functions, let's say **sub** function, I need to use **re.** before function name:

In [103]:
import re
re.sub('\W', '', 'Hey..,Wait!')

'HeyWait'

It's possible to import modules as an alias. We usually do this when either dealing with not son short library names or there is a convention to do so:

In [108]:
import statsmodels as sm
import numpy as np

Another possibility is to just import the module we need , instead of importing the whole library:

In [105]:
from pandas import Timestamp

In some rare cases we may want to import every function/module/class from a library:

In [ ]:
from pprint import *

## Installing libraries

There are 4 main ways to install a package in python:

- **conda**

conda is the package manager which is a part of Anaconda distribution (not the official Python). Respect to the native Python package managers, it manages the dependencies between different libraries is a better way. It's shortcoming is that it usually doesn't include lesser known/recent packages.

Installing a package using conda in terminal:  

        conda install package_name

Installing a package using conda in Jupyter notebook:    

        !conda install package_name


- **pip**

pip is the newest (introduced in 2008) official package manager.

Installing a package using pip in terminal:     

        pip install package_name

Installing a package using pip in Jupyter notebook:     

        !pip install package_name

- **easy_install**

easy_install is the father of pip (born in 2004) and somehow is inferior respect to the pip. (see their difference [here](https://packaging.python.org/discussions/pip-vs-easy-install/))

Installing a package using easy_install in terminal:   

        easy_install package_name

Installing a package using pip in Jupyter notebook:     

        !easy_install package_name

- **installation from source code**

I don't recommend using it but if for some reasons you want to use this method, you can find a step by step guide [here](https://kb.iu.edu/d/acey).

# Understanding errors

Regardless of your experience with Python, either you're seeing Python for the first time or you have years of coding experience, you should deal with errors, almost every time you write something! Some errors occur because due to simple reasons like writing *primt(...)* instead of *print(...)* and some are more complicated both to resolve  and to find their origin. There are way to many error types in Python for us to cover in this course but you'll find a well-written summary of important errors [here](https://www.tutorialsteacher.com/python/error-types-in-python) .
Instead of going to each and every error and explain it, I try to show you the general process of dealing with them.
Take a look at the following code:

In [112]:
my_dict = {'A':1, 'B': 2}
my_list = ['C', 'D']

for item in my_list:
    my_dict.append(my_dict)

AttributeError: 'dict' object has no attribute 'append'

**Error Translation into natural language**

>I started from the line 1 in the main **module**, I went down until line 4 without any problem. In the line 5 I saw an error of type **AttributeError**. I see this type of error because in the line 5 you tried to use **append** method on a **dictionary** which is not correct.

Now let's take a look at another example which is a bit complex respect to the previous one:

In [66]:
def add_them(a, b):
    """Add to input numbers
    args:
        a : first number
        b : second number
        
    returns:
        a number, sum of the inputs
    """
    return a + b

print(add_them('1', 2))

TypeError: can only concatenate str (not "int") to str

**Error Translation into natural language**

>I started from the line 1, I went down until line 11 without any problem. In the line 12 I saw something that wasn't correct. I tried to find the reason. I found out that the error comes from a function called **add_them**. I put your inputs in this function and went forward. when I reach to line 10 I saw an error of type **TypeError**.I see this type of error because using your input data in the line 10 you tried to concatenate a **str** to a **int** which is impossible.

**GENERAL TIPS**:

It's possible that ...

- Resolving an error, you get another error! always pay attention to the details of error.
- Even by using all the info coming from the error message we won't be able to resolve the problem. In this case you can try to search for the error message online. For sure someone else before you has arrived to the same problem and asked it online! The best source for getting help is [stackoverflow](https://stackoverflow.com) site. 

<img src="Images/student.svg"   width="30" align="left">               

**YOUR TURN**:

Run the following line of codes and try to locate and resolve the problem:

In [120]:
a, b, c, d = list(range(87, 110, 10))

ValueError: not enough values to unpack (expected 4, got 3)

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

<img src="Images/wizard.svg"   width="30" align="left">               

**YOUR TURN**:

Run the following lines of codes and try to locate and resolve the problem:

In [ ]:
city_1 = {'country': 'Italy', 'city': 'como', 'population': 84_876}
city_2 = {'country': 'Germany', 'city': 'berlin', 'population': 3_575_000}

data = []
data['IC'] = city_1
data['GB'] = city_2

ids = data.keys()
countries = []
cities = []
populations = []
for idd in ids:
    temp = data[idd]
    countries.add(temp['country'])
    cities.append(temp['city'])

print(f'There are {len(countries)} countries:')
for num, country in enumerate(countries, start=1):
    print(num, country.title(), sep=' - ')

print(f'\nand {len(cities)} cities:')
for city in enumerate(cities, start=1):
    print(num, city.title(), sep=' - ')

print()
for id in ids:
    temp = data[idd]
    print(f"{temp['city'].title()} is in {temp['country'].title()} and has a population of {temp['population']:,}.")

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

# Basics of  Pandas

<img src="Images/pandas.png" width="300"> 

Pandas is one of the mostly used libraries in Python for data cleaning, wrangling and analysis. It has a wide range of tools to deal with almost all data types and forms together with statistical and even visualization tools.
Due to large number of tools within Pandas library we're only going to see the most important parts of them together but I highly suggest the book [Python for Data Analysis](https://www.oreilly.com/library/view/python-for-data/9781491957653/) written by creator of the Pandas library [Wes McKinney](https://wesmckinney.com/). Here also you can find some good resources for Pandas: [link](https://www.dataschool.io/best-python-pandas-resources/) and of course don't forget to watch Mark Ham [YouTube Series](https://www.youtube.com/watch?v=yzIMircGU5I&list=PL5-da3qGB5ICCsgW1MxlZ0Hq8LL5U3u9y&index=2&t=232s)

Let's start discovering pandas tools working with a real dataset. 
I've already downloaded a [dataset](https://archive.ics.uci.edu/ml/datasets/Census+Income) containing US census data for year 1996.
You can find more information about this dataset and how it's been collected in the following path: 

*Intro_to_Python/Files/data/census/description.txt*

## Reading a csv file

The first thing we do is to read the csv file:

In [121]:
import pandas as pd

df = pd.read_csv('./Files/data/census/adult.csv')

<img src="Images/owl.svg"   width="40" align="left">    

***What happened in the cell above?***

**line1** : importing pandas library and giving an alias name(pd) to it

line2 : Nothing :D

**line3** : In order to read our dataset into the memory, we should use a function called **read_csv**.

why we put a "pd." before it? because we didn't import this function explicitly so we need to tell Python where can it find the **read_csv** function. Then we passed the file path as the argument. Notice that the file path is not the only argument you can pass to **read_csv** but for now, we don't need anything else.

Ok now let's take a look at the data we have just read:

In [123]:
df.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

<img src="Images/owl.svg"   width="40" align="left">    

***What happened in the cell above?***

We used a method called *.head( )* in order to see the first 5 rows of our data. Instead of living *head( )* without an argument, we can decide how many rows of the table we want to see *(Why leaving it without an argument we got 5 rows then?)*

As you may have noticed, something doesn't make sense in the result. The first row (showed in bold) should contain column labels but at the moment, it's not like this!
The reason is (and it happens a lot dealing with real data) that the original file we've received as our dataset doesn't have any column name.
Reading the description file I've mentioned before, we can find the column names:

In [128]:
col_names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num',
             'marital-status', 'occupation', 'relationship', 'race', 'sex',
             'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
            'income']

Ok, now that we have the names we can use an argument of **read_csv** called **names** to provide the column names:

In [129]:
df = pd.read_csv('./Files/data/census/adult.csv', names=col_names)

In [126]:
df.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

Perfect! it seems we've correctly added the column names to our data. While it wasn't the case this time, it can happen that the data we're dealing with has a large size and it takes time to read it again from the csv file. In this case we can add the column name after reading the raw data using the **columns** attribute:

In [12]:
df.columns = col_names

In [87]:
df.head(3)

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   

        marital-status          occupation    relationship    race    sex  \
0        Never-married        Adm-clerical   Not-in-family   White   Male   
1   Married-civ-spouse     Exec-managerial         Husband   White   Male   
2             Divorced   Handlers-cleaners   Not-in-family   White   Male   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K

## Understanding your data

Now that we have loaded our data, we should get some basic info about them to know what are the data that we're dealing with.

What is the data type of our loaded data? is it a list? a dictionary? let's find out:

In [16]:
type(df)

pandas.core.frame.DataFrame

For now, just consider the first and last words: **pandas** and **DataFrame**. It means that the file type of our imported data *df* is **DataFrame** and belongs to **pandas** library. What is **DataFrame**? It is a special file type which is not a part of Python's core data types but instead it is built on top of another Python library called **Numpy**. In a nutshell, a **DataFrame** is rectangular (tabular) data type which consists of rows and columns. these rows and columns have their our data type called **Series** which just like **DataFrame** belongs to **pandas** as is based on the **Numpy** library. The following figure shows their relationships together:

<img src="Images/dataframe.png" width="800"> 

### Shape of data

**shape** attribute returns the shape of the dataframe : 32561 rows and 15 columns:

In [15]:
df.shape

(32561, 15)

As you may remember the function **len** and how we can use it with *lists* and *strings*. We can use it also with our *DataFrame* to get the number of rows:

In [20]:
len(df)

32561

### Data preview

Just like **head( )** method used to take a peek at the first n rows of DataFrame, we can use **tail( )** method to see the last n rows:

In [21]:
df.tail(3)

age      workclass  fnlwgt education  education-num  \
32558   58        Private  151910   HS-grad              9   
32559   22        Private  201490   HS-grad              9   
32560   52   Self-emp-inc  287927   HS-grad              9   

            marital-status        occupation relationship    race      sex  \
32558              Widowed      Adm-clerical    Unmarried   White   Female   
32559        Never-married      Adm-clerical    Own-child   White     Male   
32560   Married-civ-spouse   Exec-managerial         Wife   White   Female   

       capital-gain  capital-loss  hours-per-week  native-country  income  
32558             0             0              40   United-States   <=50K  
32559             0             0              20   United-States   <=50K  
32560         15024             0              40   United-States    >50K

### Simple descriptive statistics

Using *.info( )* we can get general info of the dataframe:
    

In [ ]:
df.info()

<img src="Images/info.png" width="800"> 

In case we want to have a general idea about our data, we can use **.describe( )** method:

In [82]:
df.describe(include='all').round(1)

age workclass     fnlwgt education  education-num  \
count   32561.0     32561    32561.0     32561        32561.0   
unique      NaN         9        NaN        16            NaN   
top         NaN   Private        NaN   HS-grad            NaN   
freq        NaN     22696        NaN     10501            NaN   
mean       38.6       NaN   189778.4       NaN           10.1   
std        13.6       NaN   105550.0       NaN            2.6   
min        17.0       NaN    12285.0       NaN            1.0   
25%        28.0       NaN   117827.0       NaN            9.0   
50%        37.0       NaN   178356.0       NaN           10.0   
75%        48.0       NaN   237051.0       NaN           12.0   
max        90.0       NaN  1484705.0       NaN           16.0   

             marital-status       occupation relationship    race    sex  \
count                 32561            32561        32561   32561  32561   
unique                    7               15            6       5      2   
top      Married-civ-spouse   Prof-specialty      Husband   White   Male   
freq                  14976             4140        13193   27816  21790   
mean                    NaN              NaN          NaN     NaN    NaN   
std                     NaN              NaN          NaN     NaN    NaN   
min                     NaN              NaN          NaN     NaN    NaN   
25%                     NaN              NaN          NaN     NaN    NaN   
50%                     NaN              NaN          NaN     NaN    NaN   
75%                     NaN              NaN          NaN     NaN    NaN   
max                     NaN              NaN          NaN     NaN    NaN   

        capital-gain  capital-loss  hours-per-week  native-country  income  
count        32561.0       32561.0         32561.0           32561   32561  
unique           NaN           NaN             NaN              42       2  
top              NaN           NaN             NaN   United-States   <=50K  
freq             NaN           NaN             NaN           29170   24720  
mean          1077.6          87.3            40.4             NaN     NaN  
std           7385.3         403.0            12.3             NaN     NaN  
min              0.0           0.0             1.0             NaN     NaN  
25%              0.0           0.0            40.0             NaN     NaN  
50%              0.0           0.0            40.0             NaN     NaN  
75%              0.0           0.0            45.0             NaN     NaN  
max          99999.0        4356.0            99.0             NaN     NaN

In [127]:
df.describe()

age        fnlwgt  education-num  capital-gain  capital-loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours-per-week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

<img src="Images/owl.svg"   width="40" align="left">    

***What happened in the cell above?***

As I just said **describe( )** provides simple statistics but why we've used **include='all'** argument and **.round(1)** method?

- **include** argument by default is None and as a result we'll get the statistics only for the numerical columns
- **round(n)** is a DataFrame method which rounds the values to **n** digits. We've used it to make our result a bit more readable.

## Essential functionalities

### Slicing and filtering data

Often we want to perform a task on one single column or use it as an input for another function. Two of the easiest ways to get a single column from a dataframe are:

     df[column_name]
     df.column_name

<img src="Images/student.svg"   width="30" align="left">               

**YOUR TURN**

try to get the **capital-loss** column using both methods and explain the results.

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

Using **describe( )** method we saw that for the categorical columns we'll get the most frequent value but how can we have the frequency of all unique values of a column (similar to COUNT DISTINCT in SQL)? 

To do so we can apply **value_counts( )** method to a categorical column. for example let's see value counts in the **marital-status** column:

In [88]:
df['marital-status'].value_counts()

 Married-civ-spouse       14976
 Never-married            10683
 Divorced                  4443
 Separated                 1025
 Widowed                    993
 Married-spouse-absent      418
 Married-AF-spouse           23
Name: marital-status, dtype: int64

Adding **normalize=True** argument to **value_counts( )** method we can have the frequencies in percentage:

In [90]:
df['marital-status'].value_counts(normalize=True)

 Married-civ-spouse       0.459937
 Never-married            0.328092
 Divorced                 0.136452
 Separated                0.031479
 Widowed                  0.030497
 Married-spouse-absent    0.012837
 Married-AF-spouse        0.000706
Name: marital-status, dtype: float64

While using the above method will show us the unique values of a column, we can't directly use **.value_counts( )** method to have a list of unique values. (imagine that you want to use these values in a for loop). 
**Series** has another method called **unique( )** which returns a numpy array (not a list):

In [98]:
df['race'].unique()

array([' White', ' Black', ' Asian-Pac-Islander', ' Amer-Indian-Eskimo',
       ' Other'], dtype=object)

Often we want to slice our dataframe and somehow reduce it. We can do it either by slicing or filtering it.

Let's start from slicing. Suppose we want a subset of the original data which contains the first 8 rows and all the columns except the last one:

In [132]:
df.head(5)

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [135]:
df.iloc[1:4,3:4]

education
1   Bachelors
2     HS-grad
3        11th

<img src="Images/owl.svg"   width="40" align="left">    

***What happened in the cell above?***

We used one of DataFrame methods called **iloc[ ]** which is for **locating based on index**. Let's see the structure of a **.iloc[ ]** method:

<img src="Images/iloc.png" width="600"> 

Now let's see how can we filter our data.

Suppose that you want to filter the data to find out people who has a PhD degree and are in a farming/Fishing business:

In [39]:
df[(df.education == ' Doctorate') & (df['occupation'] == ' Farming-fishing')]

age      workclass  fnlwgt   education  education-num  \
19861   77   Self-emp-inc   84979   Doctorate             16   

            marital-status        occupation relationship    race    sex  \
19861   Married-civ-spouse   Farming-fishing      Husband   White   Male   

       capital-gain  capital-loss  hours-per-week  native-country income  
19861         20051             0              40   United-States   >50K

<img src="Images/owl.svg"   width="40" align="left">    

***What happened in the cell above?***

The general form of the code we used is : **df \[some_condition \]**

But why does it work? let's take a look at what we've called **some_condition**:

In [138]:
val = (df.education == ' Doctorate') & (df['occupation'] == ' Farming-fishing')

In [139]:
print(f'There are {len(val)} values')
print(f'The type is {type(val)}')
print('\nThe values are:\n')
print(val.value_counts())

There are 32561 values
The type is <class 'pandas.core.series.Series'>

The values are:

False    32560
True         1
dtype: int64


By running the previous cell we can understand that what we've called **some_condition** is a **Series** with length of 32,561 (= len(df)) and with 32,560 *False* and just one *True*: This condition is instructing the *df* by telling him which rows it should return (*True*) and which rows shouldn't return (*False*)

In the same way you can also filter single columns (**Series**). imagine you want to filter age column for records with more than 18 years old:

In [140]:
df.age[df.age > 18]

0        39
1        50
2        38
3        53
4        28
5        37
6        49
7        52
8        31
9        42
10       37
11       30
12       23
13       32
14       40
15       34
16       25
17       32
18       38
19       43
20       40
21       54
22       35
23       43
24       59
25       56
26       19
27       54
28       39
29       49
         ..
32531    30
32532    34
32533    54
32534    37
32535    22
32536    34
32537    30
32538    38
32539    71
32540    45
32541    41
32542    72
32543    45
32544    31
32545    39
32546    37
32547    43
32548    65
32549    43
32550    43
32551    32
32552    43
32553    32
32554    53
32555    22
32556    27
32557    40
32558    58
32559    22
32560    52
Name: age, Length: 31616, dtype: int64

<img src="Images/student.svg"   width="30" align="left">               

**YOUR TURN:**

create two separate dataframe one containing info of women and one for men, compare the percentage of *education* fields in these two dataframes.

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

In the previous example, we've used two conditions**(df.education == ' Doctorate')** and  **(df\['occupation'\] == ' Farming-fishing')** and have used a logical operator **'&'** to connect them together. But what if instead of just filtering education to be equal to *'Doctorate'* we want to add *'Assoc-acdm'*, *'Assoc-voc'*, and *'Prof-school'* too?

Of course one way would be to add more conditions to ones we already have, but it's a terrible solution!
In cases like this, similar to what we do in SQL (IN), we can filter a column based on multiple values:

In [62]:
edu = [' Doctorate', ' Assoc-acdm', ' Assoc-voc', ' Prof-school']

df[(df.education.isin(edu)) & (df['occupation'] == ' Farming-fishing')].head(4)

age          workclass  fnlwgt     education  education-num  \
460    44            Private  116632    Assoc-acdm             12   
604    35   Self-emp-not-inc  194404    Assoc-acdm             12   
894    42   Self-emp-not-inc  177307   Prof-school             15   
2200   65            Private   90377     Assoc-voc             11   

           marital-status        occupation    relationship    race    sex  \
460         Never-married   Farming-fishing       Own-child   White   Male   
604         Never-married   Farming-fishing   Not-in-family   White   Male   
894    Married-civ-spouse   Farming-fishing         Husband   White   Male   
2200   Married-civ-spouse   Farming-fishing         Husband   White   Male   

      capital-gain  capital-loss  hours-per-week  native-country  income  
460              0             0              40   United-States   <=50K  
604              0             0              40   United-States   <=50K  
894              0             0              65   United-States    >50K  
2200          6767             0              60   United-States   <=50K

But what if we want to exclude rows based on multiple values? it's really simple! Just add **~** before the condition:

In [61]:
df[~(df.education.isin(edu)) & (df['occupation'] == ' Farming-fishing')].head(4)

age          workclass  fnlwgt education  education-num  \
16    25   Self-emp-not-inc  176756   HS-grad              9   
22    35        Federal-gov   76845       9th              5   
79    31          Local-gov  125927   7th-8th              4   
227   66   Self-emp-not-inc  167687   HS-grad              9   

          marital-status        occupation relationship    race    sex  \
16         Never-married   Farming-fishing    Own-child   White   Male   
22    Married-civ-spouse   Farming-fishing      Husband   Black   Male   
79    Married-civ-spouse   Farming-fishing      Husband   White   Male   
227   Married-civ-spouse   Farming-fishing      Husband   White   Male   

     capital-gain  capital-loss  hours-per-week  native-country  income  
16              0             0              35   United-States   <=50K  
22              0             0              40   United-States   <=50K  
79              0             0              40   United-States   <=50K  
227          1409             0              50   United-States   <=50K

In the previous example we filtered the fields with the exact words but how can we filter them just with a part of a word? (similar to what we do in SQL with *Like*)

Suppose we want to filter the data for all the records that contain *'marr'* in their **'marital-status'** field:

In [54]:
df[df['marital-status'].str.contains('marr')].head(3)

age   workclass  fnlwgt   education  education-num  marital-status  \
0    39   State-gov   77516   Bachelors             13   Never-married   
8    31     Private   45781     Masters             14   Never-married   
12   23     Private  122272   Bachelors             13   Never-married   

         occupation    relationship    race      sex  capital-gain  \
0      Adm-clerical   Not-in-family   White     Male          2174   
8    Prof-specialty   Not-in-family   White   Female         14084   
12     Adm-clerical       Own-child   White   Female             0   

    capital-loss  hours-per-week  native-country  income  
0              0              40   United-States   <=50K  
8              0              50   United-States    >50K  
12             0              30   United-States   <=50K

<img src="Images/owl.svg"   width="40" align="left">    

***What happened in the cell above?***

Now we know that we're dealing with another case of **df\[some_condition\]** and expect that **some_condition** returns a Series with Boolean values. The only thing that is new here is:

**.str.contains( )**
looking at it carefully we can understand that **.contains( )** is a method of **str**. You may ask why suddenly we need to use **str**, which is a legitimate question! We should use **str**, since **Series**, doesn't have a native method to see if a given string is a part of another string, while **str** data type has this method. That's it!


### Sorting data

Sorting columns is really easy in Python: 

Suppose we want to sort *age* and *fnlwgt* in a Ascending and Descending orders. All we have to do is to use **.sort_values( )** method:

In [72]:
df.sort_values(by=['age', 'fnlwgt'], ascending=[True, False]).head()

age workclass  fnlwgt education  education-num  marital-status  \
23373   17         ?  806316      11th              7   Never-married   
27167   17   Private  721712      10th              6   Never-married   
7663    17         ?  659273      11th              7   Never-married   
15350   17         ?  634226      10th              6   Never-married   
22423   17   Private  566049      10th              6   Never-married   

           occupation relationship    race      sex  capital-gain  \
23373               ?    Own-child   White   Female             0   
27167   Other-service    Own-child   White     Male             0   
7663                ?    Own-child   Black   Female             0   
15350               ?    Own-child   White   Female             0   
22423   Other-service    Own-child   White     Male             0   

       capital-loss  hours-per-week    native-country  income  
23373             0              20     United-States   <=50K  
27167             0              15     United-States   <=50K  
7663              0              40   Trinadad&Tobago   <=50K  
15350             0              17     United-States   <=50K  
22423             0               8     United-States   <=50K

### Exporting data

Often we want to save our dataframe into csv or Excel formats. You can do so by using the following lines:

In [7]:
df.to_csv('name_i_weant.csv', index=False) # csv
df.to_excel('name_i_weant.xlsx', index=False) # Excel

## Data transformation

Sometimes we need to **apply** something (Ex. a lambda function) to a specific column of our dataframe.

Using the following general form we can achieve what we want:

**one_column.apply(a_function)**

As an example suppose that we just realized that due to a data insertion error, **fnlwgt** values had been recorded in a wrong way: all the right most digits are added by mistake and we should remove them before using these numbers for our analysis. First, let's check the data type of this column:

In [47]:
df.fnlwgt.dtype

dtype('int64')

we can see that the values are integer. It means unlike strings, we can't just slice them.

**Q:** What should we do?

**A:** We should first convert these integer values to string, remove the digit on the right and convert it to integer again.
    
**Q:** How can we do this?

**A:** By using a for loop to go through items.

**!!** WRONG! You should NEVER use a for loop for such a task!

As we've mentioned above, Series come with a handy method called apply which allows us to apply a function to a Series:

In [50]:
df.fnlwgt = df.fnlwgt.apply(lambda x : int(str(x)[:-1]))

Not always all the features presented in the raw data are useful for our analysis. Especially when dealing with large amount of data, getting rid of unuseful columns can make our processes run faster. To do so we can use **.drop( )** method.

Suppose that we didn't find **fnlwgt** column useful and we want to remove it:

In [12]:
df.drop(['fnlwgt'])

KeyError: "['fnlwgt'] not found in axis"

What just happened?! According to the error message the problem is that Python couldn't find the column we've mentioned in the axis. But what does it mean "axis"? 
"axis" coming from **numpy**, is a way to indicate columns or rows in a data table while axis=0 indicates rows and axis=1, columns. The reason we got the this error is that **.drop( )** as default uses *axis=0*, so it's normal that it gives us an error because actually there is no **fnlwgt** in row indexes. using the correct argument we get the desired results:

In [141]:
%whos

Variable        Type             Data/Info
------------------------------------------
a               int              87
age_1           int              32
age_2           int              29
age_3           int              39
age_4           int              46
ages            list             n=4
autopep8        module           <module 'autopep8' from '<...>te-packages/autopep8.py'>
b               int              97
birt_month      str              0fefefe3f34f4
birth_month     int              9
birth_year      int              1987
c               int              107
cane            int              27
canes           list             n=11
char_10         str              H
col_names       list             n=15
csv             module           <module 'csv' from '/User<...>a3/lib/python3.7/csv.py'>
d               int              117
data            list             n=100000
df              DataFrame               age          workc<...>[32561 rows x 15 columns]
file       

In [13]:
df.drop(['fnlwgt'], axis=1)

age          workclass      education  education-num  \
0       39          State-gov      Bachelors             13   
1       50   Self-emp-not-inc      Bachelors             13   
2       38            Private        HS-grad              9   
3       53            Private           11th              7   
4       28            Private      Bachelors             13   
5       37            Private        Masters             14   
6       49            Private            9th              5   
7       52   Self-emp-not-inc        HS-grad              9   
8       31            Private        Masters             14   
9       42            Private      Bachelors             13   
10      37            Private   Some-college             10   
11      30          State-gov      Bachelors             13   
12      23            Private      Bachelors             13   
13      32            Private     Assoc-acdm             12   
14      40            Private      Assoc-voc             11   
15      34            Private        7th-8th              4   
16      25   Self-emp-not-inc        HS-grad              9   
17      32            Private        HS-grad              9   
18      38            Private           11th              7   
19      43   Self-emp-not-inc        Masters             14   
20      40            Private      Doctorate             16   
21      54            Private        HS-grad              9   
22      35        Federal-gov            9th              5   
23      43            Private           11th              7   
24      59            Private        HS-grad              9   
25      56          Local-gov      Bachelors             13   
26      19            Private        HS-grad              9   
27      54                  ?   Some-college             10   
28      39            Private        HS-grad              9   
29      49            Private        HS-grad              9   
...    ...                ...            ...            ...   
32531   30                  ?      Bachelors             13   
32532   34            Private      Doctorate             16   
32533   54            Private      Bachelors             13   
32534   37            Private   Some-college             10   
32535   22            Private           12th              8   
32536   34            Private      Bachelors             13   
32537   30            Private        HS-grad              9   
32538   38            Private      Bachelors             13   
32539   71                  ?      Doctorate             16   
32540   45          State-gov        HS-grad              9   
32541   41                  ?        HS-grad              9   
32542   72                  ?        HS-grad              9   
32543   45          Local-gov     Assoc-acdm             12   
32544   31            Private        Masters             14   
32545   39          Local-gov     Assoc-acdm             12   
32546   37            Private     Assoc-acdm             12   
32547   43            Private        HS-grad              9   
32548   65   Self-emp-not-inc    Prof-school             15   
32549   43          State-gov   Some-college             10   
32550   43   Self-emp-not-inc   Some-college             10   
32551   32            Private           10th              6   
32552   43            Private      Assoc-voc             11   
32553   32            Private        Masters             14   
32554   53            Private        Masters             14   
32555   22            Private   Some-college             10   
32556   27            Private     Assoc-acdm             12   
32557   40            Private        HS-grad              9   
32558   58            Private        HS-grad              9   
32559   22            Private        HS-grad              9   
32560   52       Self-emp-inc        HS-grad              9   

               marital-status          occupation     relationship  \
0               Never-married 

Ok, it worked this time!

Let's take a **head** of our data to confirm the changes:

In [14]:
df.head(2)

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   

        marital-status        occupation    relationship    race    sex  \
0        Never-married      Adm-clerical   Not-in-family   White   Male   
1   Married-civ-spouse   Exec-managerial         Husband   White   Male   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K

What?? Why the column **fnlwgt** is still there?

There reason is that like the majority of DataFrame methods, **.drop( )** returns a modified version of data and doesn't alter the original data.
In case we are sure that we want to change the original data, we can do it in two ways. Either by assigning the result to the df variable:

In [ ]:
df = df.drop(['fnlwgt'], axis=1)

Or by using the **inplace** argument of the **drop** method:

In [ ]:
df.drop(['fnlwgt'], axis=1, inplace=True)

<img src="Images/baby.svg"   width="30" align="left">               

**YOUR TURN:**
    
Try to use both methods together. Explain the results:

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

### Removing duplicates

Another issue that frequently appears in data analysis tasks is presence of duplicated data. Based on the nature of your info these duplicated data may exist simply due to a simple glitch in ETL system or they can be a sign of a serious problem with data gathering methods. Two main methods related to duplicated data are:

- **.drop_duplicates( )** : Removal of duplicated rows
- **.duplicated( )** : showing the duplicated rows

<img src="Images/student.svg"   width="30" align="left">               

**YOUR TURN:**
    
Explain what happens in the following cell and in specific, what is the role of **keep** argument :

In [70]:
df[df.duplicated(keep=False)].sort_values(['age', 'workclass', 'fnlwgt'])

age          workclass  fnlwgt      education  education-num  \
17673   19            Private   97261        HS-grad              9   
18698   19            Private   97261        HS-grad              9   
6990    19            Private  138153   Some-college             10   
21318   19            Private  138153   Some-college             10   
15189   19            Private  146679   Some-college             10   
21490   19            Private  146679   Some-college             10   
3917    19            Private  251579   Some-college             10   
31993   19            Private  251579   Some-college             10   
5805    20            Private  107658   Some-college             10   
11631   20            Private  107658   Some-college             10   
8080    21            Private  243368      Preschool              1   
15059   21            Private  243368      Preschool              1   
4767    21            Private  250051   Some-college             10   
9171    21            Private  250051   Some-college             10   
21103   23            Private  240137        5th-6th              3   
25872   23            Private  240137        5th-6th              3   
5842    25            Private  195994        1st-4th              2   
13084   25            Private  195994        1st-4th              2   
22300   25            Private  195994        1st-4th              2   
4325    25            Private  308144      Bachelors             13   
4881    25            Private  308144      Bachelors             13   
5579    27            Private  255582        HS-grad              9   
28230   27            Private  255582        HS-grad              9   
8679    28            Private  274679        Masters             14   
26313   28            Private  274679        Masters             14   
16975   30            Private  144593        HS-grad              9   
18555   30            Private  144593        HS-grad              9   
16846   35            Private  379959        HS-grad              9   
32404   35            Private  379959        HS-grad              9   
4940    38            Private  207202        HS-grad              9   
29157   38            Private  207202        HS-grad              9   
25624   39            Private   30916        HS-grad              9   
28846   39            Private   30916        HS-grad              9   
10367   42            Private  204235   Some-college             10   
28522   42            Private  204235   Some-college             10   
17916   44            Private  367749      Bachelors             13   
22367   44            Private  367749      Bachelors             13   
11965   46            Private  133616   Some-college             10   
30845   46            Private  133616   Some-college             10   
16297   46            Private  173243        HS-grad              9   
17040   46            Private  173243        HS-grad              9   
7920    49            Private   31267        7th-8th              4   
21875   49            Private   31267        7th-8th              4   
7053    49   Self-emp-not-inc   43479   Some-college             10   
22494   49   Self-emp-not-inc   43479   Some-college             10   
2303    90            Private   52386   Some-college             10   
5104    90            Private   52386   Some-college             10   

            marital-status          occupation    relationship  \
17673        Never-married     Farming-fishing   Not-in-family   
18698        Never-married     Farming-fishing   Not-in-family   
6990         Never-married        Adm-clerical       Own-child   
21318        Never-married        Adm-clerical       Own-child   
15189        Never-married     Exec-managerial       Own-child   
21490        Never-married     Exec-managerial       Own-child   
3917         Never-married       Other-service       Own-child   
31993        Never-married       Other-service       Own-child   
5805

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

### Handling missing data

Working with real data, it's almost impossible to have a dataset with no missing data. Missing data exist due to different reasons:

- Error in recording the data (so the data actually exist but is not recorded)
- The person/team who created the dataset wasn't/weren't able to get those specific values.

Ok, let's try to identify missing data in our dataframe. Both DataFrame and Series types have **.isnull( )** and **.notnull( )** methods. First we'll try to check one column for missing data:

In [15]:
df['workclass'].isnull()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...  
32531    False
32532    False
32533    False
32534    False
32535    False
32536    False
32537    False
32538    False
32539    False
32540    False
32541    False
32542    False
32543    False
32544    False
32545    False
32546    False
32547    False
32548    False
32549    False
32550    False
32551    False
32552    False
32553    False
32554    False
32555    False
32556    False
32557    False
32558    False
32559    False
32560    False
Name: workclass, Length: 32561, dtype: bool

Ok, maybe it's not what we were expecting to see! As far as we can see, the answer to ***isnull*** was **False**. But it's not a good way since a part from being too long to read, the result is truncated so we can't actually see all the values. We can apply one of two following methods to summarize the result:

- summing the values
- use built-in functions *any* and *all*

In [17]:
df['workclass'].isnull().sum()

0

<img src="Images/owl.svg"   width="40" align="left">    

***What happened in the cell above?***

As you may remember, learning about Boolean data types we saw that Python considers True value as 1 and False values as 0. The output of cell above shows that the result of summation of all values is 0, it means not even one value is *True*.

In [18]:
df['workclass'].isnull().any()

False

<img src="Images/owl.svg"   width="40" align="left">    

***What happened in the cell above?***

**any( )** is a built-in function which applied on a sequence returns *True* if there is *at least* ONE *True* value. The output of cell above shows that no *True* was found.

<img src="Images/baby.svg"   width="30" align="left">               

**YOUR TURN:**
    
Try to use **notnull( )** and **all( )** to do the same control we did above:

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

Ok it seems **workclass** column doesn't have any missing value. Now let's check the entire dataframe and found out which columns have *null* values. As we said before, like **Series**, **DataFrames**s also have **isnull( )** and **notnull( )**.

In [20]:
df.isnull().sum() # try to remove sum() and see the result

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

Wow! it seems we don't have a single missing value in the whole dataframe! The problem is that consulting with the description file comes with the dataset, we'll find this:
    
**'3. Convert Unknown to "?"'**

*(Note: you almost never find such a file in the real world!)*

So, it's means we're not that lucky after all! we can confirm this by applying a **.value_counts( )** on **workclass** column:

In [21]:
df['workclass'].value_counts()

 Private             22696
 Self-emp-not-inc     2541
 Local-gov            2093
 ?                    1836
 State-gov            1298
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: workclass, dtype: int64

Fantastic! we have 1836 missing values just in this column alone!

While identifying missing data is almost straight forward, making decisions about them is not quite easy!
There are different strategies to deal with missing data but there is no CORRECT answer here:

- ignoring them
- removing them
- replace them with another value

Except the first method, choosing the other two methods bring us to other choices like what exactly we should remove? the whole row? when should we do it, when at least one value is missing or more ? or what should be used to fill the missing data, average of the other values? the last present value?

As you can see these choices are by no means easy to make and most of the time, any decision will dramatically affect your results. This is were a good knowledge of domain and statistics is needed.

Ok, let's see how can we apply these methods to our dataframe, starting from removal of missing data:

In [27]:
len(df) - len(df.dropna())

0

<img src="Images/baby.svg"   width="30" align="left">               

**YOUR TURN:**
    
Explain the code above and its result.

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

It seems we can't go forward with missing value methods before doing a certain data transformation. Can you guess what would be this transformation? Exactly! we should replace **?** values with null values. so we're going to need:
    
- A method to replace a value with another one in a dataset $\rightarrow$ **.replace( )**
- An object that represents the null value $\rightarrow$ **numpy.nan**

In [29]:
df_miss = df.replace(to_replace='?', value=np.nan)

Let's check if it worked:

In [34]:
df_miss.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

Nope! :( but why? It seems that we should have used wasn't ""?""...""? "" maybe?

Let's check it out:

In [35]:
for item in df.workclass.unique():
    print(item.replace(' ','_'))

_State-gov
_Self-emp-not-inc
_Private
_Federal-gov
_Local-gov
_?
_Self-emp-inc
_Without-pay
_Never-worked


Aha! So there is a space before **?**    !

In [40]:
df_miss = df.replace(to_replace=' ?', value=np.nan)

In [41]:
df_miss.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
income               0
dtype: int64

Finally! Now that we have replaced ? with **Null** values, we can apply **.dropna( )**

In [44]:
df_drop = df_miss.dropna()
print(len(df_drop))

30162


We've lost 30162 rows of dataset.

In [53]:
print(f'Which is about {round((len(df) - len(df_drop)) / len(df), 4) * 100}% of data.')

Which is about 7.37% of data.


<img src="Images/wizard.svg"   width="30" align="left">               

**YOUR TURN:**
    
Try to understand how can you use **how**, **thresh** and  **subset** arguments of **dropna( )** method.

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

Using **.fillna( )** you can fill the the missing values with a desired value. In the next cell we fill them with a **_** character:

In [59]:
df_dashed = df_miss.fillna('-')

In [60]:
df_dashed.sample(4)

age          workclass  fnlwgt   education  education-num  \
6852   32            Private  604506     HS-grad              9   
9124   33   Self-emp-not-inc  281030     HS-grad              9   
106    17                  -  304873        10th              6   
8439   37            Private  155064   Assoc-voc             11   

           marital-status         occupation relationship    race      sex  \
6852   Married-civ-spouse   Transport-moving    Own-child   White     Male   
9124   Married-civ-spouse    Farming-fishing      Husband   White     Male   
106         Never-married                  -    Own-child   White   Female   
8439             Divorced     Prof-specialty    Unmarried   White   Female   

      capital-gain  capital-loss  hours-per-week  native-country  income  
6852             0             0              72          Mexico   <=50K  
9124             0             0              94   United-States   <=50K  
106          34095             0              32   United-States   <=50K  
8439             0             0              40   United-States   <=50K

<img src="Images/wizard.svg"   width="30" align="left">               

**YOUR TURN:**
    
Write a function that loops through all columns with missing values and if the column data type is numerical, fills the missing data with median of the column.

In [ ]:
(\   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   /_")
 \\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//^\\_//
  `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`   `"`

# Intermediate and Advanced topics

## Docstrings and Comments

## List comprehension

## Dictionary comprehension

## Zip and enumerate

## Content Managers

## Basic Plotting

## Navigation and paths

### Current directory

### Changing current directory

### Absolute and Relative paths

## Error Handling

In section 8 and 12 we've seen some examples of Syntax and Exception errors and we also saw how can we *Translate* error messages into *human language*. In this part we will have deeper look on errors and how can we __handle__ them.

First, let's have a recap of different types of errors:

__Syntax Error__

In [64]:
my_string = 'It's 6 AM and I'm already working!'
print(my_string)

SyntaxError: invalid syntax (<ipython-input-64-ad95df0c582c>, line 1)

__Exception Error__

In [7]:
some_list = [x[0] for x in [55, 'foo', 'bar', 42]]
print(some_list)

TypeError: 'int' object is not subscriptable

<img src="Images/student.svg"   width="30" align="left">               

**YOUR TURN:**
    
Re-write the above code blocks in a correct way (no error is needed!)

In [65]:
my_string = "It's 6 AM and I'm already working!"
print(my_string)
some_list = [str(x)[0] for x in [55, 'foo', 'bar', 42]]
print(some_list)

It's 6 AM and I'm already working!
['5', 'f', 'b', '4']


### Raising your own Exceptions

We saw how Python uses __Exceptions__ to show you are doing something wrong. In the same way you can __raise__ your own exceptions to warn users and stop the code.

Let's make a function which gets a string as ___"name surname"__ and prints out __"Your name is name and your surname is surname"__

In [17]:
def simple_fun(text):
    """gets a string of name and surname separeted by space and prints them in a template"""
    
    # splitting the string by space
    name, surname = text.split(' ',1)
    print(f'Your name is {name} and your surname is {surname}')

In [18]:
simple_fun('Mimmo Paladino')

Your name is Mimmo and your surname is Paladino


But what happens if someone gives just her name or surname instead?

In [19]:
simple_fun('Oliver')

ValueError: not enough values to unpack (expected 2, got 1)

The error we get is a __ValueError__ and is indicating that we passed just one input while Python was expecting 2.
While it may seems easy to understand, for a someone who doesn't know python (or simply is not familiar with your code) may not be so simple to understand what causes the error. We can solve this problem by raising a custom Exception in our function.

In [24]:
def simple_fun(text):
    """gets a string of name and surname separeted by space and prints them in a template"""
    
    if ' ' not in text :
        raise Exception("It seems you just entered your name or surname. I need something like this : 'Rickey Gervais'")
    
    # splitting the string by space
    name, surname = text.split(' ', 1)
    print(f'Your name is {name} and your surname is {surname}')

Let's check it to see if it works

In [28]:
simple_fun('Oliver')

Exception: It seems you just entered your name or surname. I need something like this : 'Rickey Gervais'

__General Form__

<img src="Images/exception.png" width="800"> 

### Assertion

To achieve what we did with Exception raising, we can use another method which is __Assertion__. It's simply a *control for a condition*:

In [37]:
def simple_fun(text):
    """gets a string of name and surname separeted by space and prints them in a template"""
    
    assert(' ' in text), "It seems you just entered your name or surname. I need something like this : 'Rickey Gervais'"
    
    # splitting the string by space
    name, surname = text.split(' ', 1)
    print(f'Your name is {name} and your surname is {surname}')

In [38]:
simple_fun('Oliver')

AssertionError: It seems you just entered your name or surname. I need something like this : 'Rickey Gervais'

<img src="Images/wizard.svg"   width="30" align="left">               

**YOUR TURN:**
    
Use Exception raising to write a function that gets a number in centimeter and convert it to inch unit. This function should be able to warn user if the input is not a number.

- Hint 1 : a number in this case can be either integer of float
- Hint 2 : 1 cm is 0.393701 inch

In [54]:
def cm2inch(num):
    if type(num) != float and type(num) != int:
        raise Exception(f'Please enter an integer or float not a {type(num)}')
    return num * 0.393701

In [56]:
cm2inch('cane')

Exception: Please enter an integer or float not a <class 'str'>

<img src="Images/wizard.svg"   width="30" align="left">               

**YOUR TURN:**
    
Use Assertion instead of raising an Exception

In [59]:
def cm2inch(num):
    assert (type(num) == float or type(num) == int),f'Please enter an integer or float not a {type(num)}'
    return num * 0.393701

In [62]:
cm2inch('cane')

AssertionError: Please enter an integer or float not a <class 'str'>

__General form__

<img src="Images/assertion.png" width="800"> 

### Try/Except

While Exception raising and assertion are helpful ways to assure the code is behaving in the desired way, they don't actually _handle_ errors as the code crashes no matter the exception/assertion.

That's where try and except blocks come in the scene!

Let's see an example:

In [80]:
from pprint import pprint

info = {'id_1': {'name': 'Fabio M', 'debt': 67_000, 'balance': 10_000},
       'id_2': {'name': 'Mario M', 'debt': 0, 'balance': 350_000},
       'id_3': {'name': 'Ale V', 'debt': 100, 'balance': 60_000},
       'id_4': {'name': 'Mauro', 'debt': 130, 'balance': 100_000}}

ids = info.keys()
for iid in ids:
    info[iid]['new_val'] = round(info[iid]['balance'] / info[iid]['debt'], 1)

pprint(info)

ZeroDivisionError: division by zero

We're getting ZeroDivisionError and it's crashing our code. We can use try/except to catch the exception:

In [82]:
info = {'id_1': {'name': 'Fabio M', 'debt': 67_000, 'balance': 10_000},
       'id_2': {'name': 'Mario M', 'debt': 0, 'balance': 350_000},
       'id_3': {'name': 'Ale V', 'debt': 100, 'balance': 60_000},
       'id_4': {'name': 'Mauro ', 'debt': 130, 'balance': 100_000}}

ids = info.keys()
for iid in ids:
    try:
        info[iid]['new_val'] = round(info[iid]['balance'] / info[iid]['debt'], 1)
        
    except ZeroDivisionError:
        info[iid]['new_val'] = 0
        
pprint(info)

{'id_1': {'balance': 10000, 'debt': 67000, 'name': 'Fabio ', 'new_val': 0.1},
 'id_2': {'balance': 350000, 'debt': 0, 'name': 'Mario', 'new_val': 0},
 'id_3': {'balance': 60000, 'debt': 100, 'name': 'Ale', 'new_val': 600.0},
 'id_4': {'balance': 100000, 'debt': 130, 'name': 'Mauro', 'new_val': 769.2}}


As you can see, unlike last time, our code finished its job , we just handled an error!

We can use more than one exception type:

In [84]:
info = {'id_1': {'name': 'Fabio M', 'debt': 67_000, 'balance': 10_000},
       'id_2': {'name': 'Mario M', 'debt': 0, 'balance': 350_000},
       'id_3': {'name': 'Ale V', 'debt': 100, 'balance': 60_000},
       'id_4': {'name': 'Mauro ', 'debt': 130, 'balance': 100_000}}

ids = info.keys()
for iid in ids:
    try:
        info[iid]['new_val'] = round(info[iid]['balance'] / info[iid]['debt'], 1)
        
    except ZeroDivisionError:
        info[iid]['new_val'] = 0
    
    try:
        name, surname = info[iid]['name'].split()
        info[iid]['name'] = name
        info[iid]['surname'] = surname
    except ValueError:
        info[iid]['surname'] = ''
        
pprint(info)

{'id_1': {'balance': 10000,
          'debt': 67000,
          'name': 'Fabio',
          'new_val': 0.1,
          'surname': 'M'},
 'id_2': {'balance': 350000,
          'debt': 0,
          'name': 'Mario',
          'new_val': 0,
          'surname': 'M'},
 'id_3': {'balance': 60000,
          'debt': 100,
          'name': 'Ale',
          'new_val': 600.0,
          'surname': 'V'},
 'id_4': {'balance': 100000,
          'debt': 130,
          'name': 'Mauro ',
          'new_val': 769.2,
          'surname': ''}}


__General form__

<img src="Images/try_except.png" width="600"> 

You can use except without specifying any particular exception.__It's a bad idea! Don't use such a thing unless you are desperate!__

### Else/Finally

There are other to statements which can be used within try/except block which are *else* and *finally*. Let's see an example:

In [97]:
data_1 = [('89768745', 2), ('87443665', -1), ('45789345', '1')]
data_2 = [('89768745', 2), ('87443665', -1), ('45789345', 1)]

try:
    for item in data_1:
        print(f'answer  : {item[0][item[1]]}')
        
except TypeError:
    print(f'wrong index --> {item[0]}')
    
else:
    print('All pairs are valid')

finally:
    print('\nAll pairs are controlled')
    
print('-' * 50)

try:
    for item in data_2:
        print(f'answer  : {item[0][item[1]]}')
        
except TypeError:
    print(f'wrong index --> {item[0]}')
    
else:
    print('All pairs are valid')

finally:

    print('\nAll pairs are controlled')

answer  : 7
answer  : 5
wrong index --> 45789345

All pairs are controlled
--------------------------------------------------
answer  : 7
answer  : 5
answer  : 5
All pairs are valid

All pairs are controlled


__General form__

<img src="Images/tryexceptelsefinally.png" width="500"> 

## Virtual environments

### Creating your custom venv

### Activating and deactivating venvs

## Iterators and Generators

## Object Oriented Programming

### Class and Object definition

### Methods and Attributes

# Resources